import { notFound } from "next/navigation";

const pages:Record<string,{title:string;body:string[]}> = {
  privacy:{title:"Privacy Policy",body:["OCL Health is being built with privacy and security as core requirements. The production privacy policy will describe what account, order, support, newsletter and optional health-tool information is collected and why.","Customer information will only be accessible to authorised systems and team members for legitimate platform purposes. Sensitive information will not be exposed through public APIs.","The final policy will identify service providers, retention practices, user rights, cookies, security controls and contact routes before customer accounts go live."]},
  terms:{title:"Terms of Service",body:["These terms will govern access to OCL Health, the marketplace, accounts, content, developer services and future platform features.","Health information published by OCL is educational and is not a substitute for professional diagnosis, treatment or emergency care.","Production terms will be reviewed against the final business model, payment flows, regulated-product workflows and applicable law before launch."]},
  refund:{title:"Refund Policy",body:["OCL will publish clear refund, cancellation and return rules before paid marketplace transactions are enabled.","Refund eligibility will depend on the product, order status, delivery status, payment method and applicable consumer and pharmacy requirements.","No production refund promise is being made by this foundation page; the final policy will be displayed at checkout and in customer accounts."]},
  "code-of-conduct":{title:"Code of Conduct",body:["OCL aims to maintain a respectful, safe and professional environment for customers, healthcare professionals, developers and team members.","Harassment, abuse, impersonation, fraudulent activity, harmful medical misinformation and misuse of the platform are not acceptable.","Reports will be handled through the future OCL support and moderation workflow."]},
  ads:{title:"Advertising Policy",body:["OCL may use advertising and Google AdSense where the business, content and advertising accounts are eligible.","Advertisements will not be presented as professional medical advice or as an endorsement by a healthcare professional unless such endorsement is genuine and properly disclosed.","Health claims, regulated products and advertising placements will be reviewed before production use."]},
  "medical-disclaimer":{title:"Medical Disclaimer",body:["OCL Health provides educational and informational content. It is not a replacement for diagnosis, treatment or advice from a qualified healthcare professional.","Do not delay urgent medical care because of information found on OCL. In an emergency, contact appropriate emergency services or a qualified healthcare professional.","OCL will not use an ordinary phone fingerprint sensor as a blood-pressure diagnostic instrument. Future health measurements will rely on validated devices, supported integrations or user-entered readings."]}
};

export async function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export default async function LegalPage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const page=pages[slug]; if(!page) notFound();
  return <main className="legalPage"><header className="portalNav"><a className="brand" href="https://www.ocl.it.com"><span className="brandMark">✚</span><span>OCL <b>Health</b></span></a><a href="https://www.ocl.it.com">Main site →</a></header><article><span className="eyebrow">OCL HEALTH • LEGAL</span><h1>{page.title}</h1>{page.body.map((p,i)=><p key={i}>{p}</p>)}</article></main>;
}
